apiVersion: v1
data:
  htpasswd: ZGV2ZWxvcGVyOiRhcHIxJDYzNUFESlBNJFF1L3oyMmdva3ZQajZRYlk3SDdEcDAKdXNlcjE6JGFwcjEkeHZKNklIYnkkOHZUVjg1dEtEd0VNQVlFaVNXN3lUMAp1c2VyMjokYXByMSRQMTNZeHB5TyRPYkZlcE9laEtsRnY1TVdpZHVzODExCmFkbWluOiRhcHIxJGNyeDNZSFlIJFYzbnZSZ0ZxT2o3SjNiSGFGdGw5eTAK
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
