apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: selenium
  name: centos
  namespace: cicd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/centos/s2i-base-centos7
    importPolicy: {}
    name: centos7
    referencePolicy:
      type: Source
