apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: cicd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: The SonarQube Docker image
      tags: sonarqube
    from:
      kind: DockerImage
      name: openshiftdemos/sonarqube:7.0
    importPolicy: {}
    name: "7.0"
    referencePolicy:
      type: Source
