apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: jenkins-slave-npm
    role: jenkins-slave
  name: jenkins-slave-npm
  namespace: cicd
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/pittar/jenkins-slave-npm:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
